# Generated by Django 4.2.6 on 2023-10-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_account_number_kyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
    ]
