# Generated by Django 4.2.6 on 2023-10-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_contact_kyc_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(default='default.jpg', upload_to='kyc'),
        ),
    ]
